"""
Django settings for roblox project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-iuqh9j-h+@xthmbg(q$sxlqfg-1z-we79(%b7ibo=uv7%1y=f3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ninetynine_days_in_the_forest',
    'the_deer',
    'wood',
    'tree',
    'frogs',
    'the_owl',
    'the_ram',
    'red_key',
    'blue_key',
    'grey_key',
    'yellow_key',
    'frog_keys',
    'the_bat',
    'basketball',
    'old_boot',
    'fairy',
    'mushroom_house',
    'fire',
    'scorpion',
    'raygun',
    'seeds',
    'regular_bed',
    'treehouse',
    'river',
    'scythe',
    'fishing_rod',
    'sled',
    'king_cultist',
    'kiwi',
    'iceskate',
    'humiliation',
    'snowball',
    'katana',
    'kunai',
    'shark',
    'bear_trap',
    'bear',
    'bear_pelt',
    'wolf',
    'wolf_pelt',
    'artic_fox',
    'articfox_pelt',
    'mammoth',
    'mammoth_tusk',
    'ufo',
    'alien',
    'bio_fuel',
    'bbq_ribs',
    'ax',
    'hammer',
    'good_bed',
    'good_wolf',
    'healthbar',
    'forest_gem',
    'lava_pools',
    'map',
    'compass',
    'flashlight',
    'crafting_bench1',
    'crafting_bench2',
    'crafting_bench3',
    'crafting_bench4',
    'crafting_bench5',
    'cooked_steak',
    'cooked_mackrel',
    'cooked_salmon',
    'cooked_shark',
    'cooked_ribs',
    'cooked_char',
    'cooked_lionfish',
    'cooked_morsel',
    'cooked_swordfish',
    'cooked_eel',
    'cooked_clownfish',
    'cooked_lava_eel',
    'cooked_turkey',
    'cooked_turkeyleg',
    'cotton_candy',
    'candy_apple',
    'carrot_cake',
    'casserole',
    'chair
    'char',
    'coal',
    'clownfish',
    'coins',
    'chilli',
    'caves',
    'cave_flower',
    'chefs_station',
    'lionfish',
    'morsel',
    'pumpkin_pie',
    'swordfish',
    'eel',
    'carrot',
    'cake',
    'carnival_ticket',
    'balloon',
    'dripleaf',
    'turkey',
    'turkey_leg',
    'turkey_legs',
    'ufo_component',
    'wolf_guard',
    'washing_machine',
    'vammpire_cloak',
    'witch_potion',
    'ufo_junk',
    'ufo_scrap',
    'utility_hammer',
    'watering_can',
    'metal_chair',
    'weather_machine',
    'vampire_scythe',
    'tyre',
    'wildfire_throwable',
    'vanilla_crossbow',
    'trident',
    'torch',
    'thorn_body',
    'thanksgiving_meal',
    'Thanksgiving_accessories',
    'Temporal_Accelerometer',
    'teleporter',
    'tactical_shotgun',
    'sweet_potato',
    'support_notes',
    'sun_dial',
    'stuffing_bowl',
    'stuffing',
    'stuffed_potatoes',
    'strong_rod',
    'strong_flute',
    'strong_flashlight',
    'stew',
    'steak_dinner',
    'stareweed_petal',
    'star_key',
    'spicy_swordfish',
    'spear',
    'snow_biome',
    'shovel',
    'shelf',
    'shark_food',
    'shadow_cultist',
    'seasoning',
    'seafood',
    'scrap_metal',
    'scrap',
    'scorpion_shell',
    'Scalding_Obsidiron_Ingot',
    'sappling',
    'salmon',
    'sacrifice_totem',
    'riot_shield',
    'ribs',
    'respawn_capsule',
    'resource_hotspot',
    'recipe_book',
    'rain_storage',
    'radar',
    'pumpkin_soup',
    'pumpkin',
    'purple_potion',
    'purple_fur'
    'potato_pie',
    'polar_bearpelt',
    'polar_bear',
    'poison_spear',
    'poison_armor',
    'party_hat',
    'paint',
    'old_sack',
    'old_radio',
    'Obsidiron_Ingot',
    'obsidiron_ore',
    'old_flute',
    'old_engine',
    'old_bed',
    'oil_drill',
    'oil_barrels',
    'obsidiron_hammer',
    'obsidiron_chest_blueprint',
    'obsidiron_armor',
    'obsidiron_boots',
    'notice'
    'morningstar',
    'moonflower_bulb',
    'meteor_shard',
    'meteor_crab',
    'mega_cultist',
    'medkit',
    'meat_sandwich',
    'mandrake',
    'mammoth_helmet',
    'log',
    'log_wall',
    'lightning_rod',
    'leather_body',
    'lava_eel',
    'laser_sword',
    'laser_rod',
    'laser_cannon',
    'ladder',
    'lake',
    'jellyfish',
    'jaro_jelly',
    'iron_body',
    'infernal_sword',
    'infernal_crossbow',
    'infernal_sack',
    'ice_sword',
    'ice_rod',
    'hollogram_emitter',
    'hellephant',
    'hearty_stew',
    'halloween_guy'
    'halloween_candle',
    'halloween_blueprint',
    'green_potion',
    'good_rod',
    'good_flute',
    'gold_shard',
    'giant_sack',
    'giant_bed',
    'fuel_canisters',
    'frozen_shuriken',
    'frozen_lake',
    'frog_boots',
    'fridge',
    'fox_hat',
    'forest',
    'foodseasoning_effect',
    'flower',
    'flamethrower',
    'feather',
    'farm_plot',
    'fake_santa'
    'event_zones',
    'event_foods',
    'ear_muffs',
    'defence_blueprint',
    'dark_forest',
    'cultistking_antler',
    'cultist_kingmace',
    'cultist_staff',
    'cultist_gem',
    'cultist',
    'cultist_expirement',
    'crockpot',
    'crafting_blueprint',
    'crafting',
    'corpse_fuel',
    'corn',
    'corn_cob',
    'christmas_lights',
    'carnival_rings',
    'carnival_basketball',
    'candy_corn',
    'camps',
    'cabins',
    'bunny_trap',
    'bunny_meat',
    'bunnies',
    'bunny_foot',
    'brute_cultist',
    'broken_microwave',
    'broken_fan',
    'broken_antler',
    'boss_areas',
    'boost_pad',
    'bolt',
    'blowpipe',
    'biofuel_prosessor',
    'berry_juice',
    'berry',
    'bear_monster',
    'bear_hat',
    'beanie',
    'bandage',
    'axe_trim_kit',
    'armor_trim_kit',
    'apple',
    'anvil',
    'amo',
    'ammo',
    'alpha_wolfpelt',
    'alpha_wolf',
    'alpha_wolf_guard',
    'alien_armor',
    'admin_sack',
    'admin_axe',
    ]
MIDDLEWARE= [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'roblox.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'roblox.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
